from __future__ import annotations

from importlib import import_module

__all__ = [
    "Artifact",
    "CheckpointRecord",
    "CheckpointSummary",
    "Finding",
    "FindingArtifactLink",
    "FindingStatus",
    "Job",
    "JobLogEntry",
    "JobLogLevel",
    "JobStatus",
    "MemoryEntry",
    "RiskLevel",
    "ConfirmationMode",
    "ConfirmationDecisionStatus",
    "ActionRiskPolicy",
    "CapabilityExecutionMetadata",
    "CapabilityExecutionStyle",
    "CapabilityKind",
    "CapabilityManifest",
    "CapabilityParameter",
    "CapabilityParameterType",
    "CapabilityRiskMetadata",
    "CapabilitySessionSupport",
    "CapabilityToolPolicy",
    "LoadedCapability",
    "ModuleExecutionPlan",
    "ModuleExecutionStep",
    "ModuleInvocationRequest",
    "RiskPolicyLimits",
    "RiskPolicyConfig",
    "ConfirmationRequestPayload",
    "ConfirmationDecision",
    "ConversationContext",
    "Run",
    "RunStatus",
    "SessionLogLevel",
    "SessionLogEntry",
    "Report",
    "ReportArtifactLink",
    "ReportFindingLink",
    "Session",
    "SessionEvent",
    "SessionEventLevel",
    "SessionEventType",
    "SessionMode",
    "SessionPersistenceMode",
    "SessionStatus",
    "SessionTarget",
    "SessionTargetKind",
    "ScopePolicy",
    "StoredCheckpoint",
]

_EXPORTS = {
    "Artifact": ".artifact",
    "CheckpointRecord": ".checkpoint",
    "CheckpointSummary": ".checkpoint",
    "StoredCheckpoint": ".checkpoint",
    "Finding": ".finding",
    "FindingStatus": ".finding",
    "FindingArtifactLink": ".finding_artifact_link",
    "Job": ".job",
    "JobLogEntry": ".job",
    "JobLogLevel": ".job",
    "JobStatus": ".job",
    "MemoryEntry": ".memory",
    "RiskLevel": ".risk_policy",
    "ConfirmationMode": ".risk_policy",
    "ConfirmationDecisionStatus": ".risk_policy",
    "ActionRiskPolicy": ".risk_policy",
    "CapabilityExecutionMetadata": ".capability",
    "CapabilityExecutionStyle": ".capability",
    "CapabilityKind": ".capability",
    "CapabilityManifest": ".capability",
    "CapabilityParameter": ".capability",
    "CapabilityParameterType": ".capability",
    "CapabilityRiskMetadata": ".capability",
    "CapabilitySessionSupport": ".capability",
    "CapabilityToolPolicy": ".capability",
    "LoadedCapability": ".capability",
    "ModuleExecutionPlan": ".capability",
    "ModuleExecutionStep": ".capability",
    "ModuleInvocationRequest": ".capability",
    "RiskPolicyLimits": ".risk_policy",
    "RiskPolicyConfig": ".risk_policy",
    "ConfirmationRequestPayload": ".risk_policy",
    "ConfirmationDecision": ".risk_policy",
    "ConversationContext": ".conversation_context",
    "Run": ".run",
    "RunStatus": ".run",
    "SessionLogLevel": ".run",
    "SessionLogEntry": ".run",
    "Report": ".report",
    "ReportArtifactLink": ".report_artifact_link",
    "ReportFindingLink": ".report_finding_link",
    "Session": ".session",
    "SessionEvent": ".session_event",
    "SessionEventLevel": ".session_event",
    "SessionEventType": ".session_event",
    "SessionMode": ".session",
    "SessionPersistenceMode": ".session",
    "SessionStatus": ".session",
    "SessionTarget": ".session",
    "SessionTargetKind": ".session",
    "ScopePolicy": ".scope_policy",
}


def __getattr__(name: str) -> object:
    module_name = _EXPORTS.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module = import_module(module_name, __name__)
    value = getattr(module, name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))
